04_django/day18/day16/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from day16 import settings
from day16app import views
from day16app.views import dep_view,user_view,pretty_view,home_view,admin_view,acc_view,task_view

urlpatterns = [
          # path('admin/', admin.site.urls),
          path('', home_view.home),
          path('index/', home_view.index),
          # 部门管理相关路由
          path('dep/list/', dep_view.dep_list),
          path('dep/add/', dep_view.dep_add),
          path('dep/del/', dep_view.dep_del),
          # 路由格式 :http://127.0.0.1:8000/dep/1/edit
          path('dep/<int:nid>/edit/', dep_view.dep_edit),

          # 员工管理相关路由
          path('user/list/', user_view.user_list),
          path('user/add/', user_view.user_add),
          path('user/<int:nid>/edit/', user_view.user_edit),
          path('user/<int:nid>/del/', user_view.user_del),

          # 靓号管理相关路由
          path('pretty/list/', pretty_view.pretty_list),
          #添加靓号
          path('pretty/add/', pretty_view.pretty_add),
          #修改靓号
          path('pretty/<int:nid>/edit/', pretty_view.pretty_edit),
          # 删除靓号
          path('pretty/<int:nid>/del/', pretty_view.pretty_del),
          #管理员账户管理
          #管理员列表
          path('admin/list/',admin_view.admin_list),
          # 新增管理员
          path('admin/add/',admin_view.admin_add),
          # 编辑管理员信息
          path('admin/<int:nid>/edit/',admin_view.admin_edit),
          # 重置管理员密码
          path('admin/<int:nid>/reset/',admin_view.admin_reset),
          # 删除管理员
          path('admin/<int:nid>/del/',admin_view.admin_del),

          #登录相关路由
          path('login/',acc_view.login),
          # 注销或者说退出登录
          path('logout/',acc_view.logout),
          # 动态生成验证码的路由
          path("image/code/",acc_view.image_code),

          # ajax测试任务管理
          path("task/test/list",task_view.task_test_list),
          path("task/test/ajax/",task_view.task_test_ajax),
          # ajax 请求发送表单数据
          path("task/test/ajax2/",task_view.task_test_ajax2),
          # 任务管理
          path("task/list/",task_view.task_list),
          path("task/ajax/",task_view.task_ajax),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

04_django/day20/day16/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls.static import static
from django.views.static import serve

from day16 import settings
from day16app import views
from day16app.views import dep_view,user_view,pretty_view,home_view,admin_view,acc_view,task_view,order_view,chart_view,upload_view,city_view

urlpatterns = [
          # path('admin/', admin.site.urls),
          # 注意:这个serve函数,在很多包里面都有,这里需要django.views.static.serve
          re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT},name='media'),
          path('', home_view.home),
          path('index/', home_view.index),
          # 部门管理相关路由
          path('dep/list/', dep_view.dep_list),
          path('dep/add/', dep_view.dep_add),
          path('dep/del/', dep_view.dep_del),
          # 路由格式 :http://127.0.0.1:8000/dep/1/edit
          path('dep/<int:nid>/edit/', dep_view.dep_edit),
          # 处理excel文件上传,然后把他的数据添加到数据库中
          path("dep/multiadd/",dep_view.dep_multiadd),

          # 员工管理相关路由
          path('user/list/', user_view.user_list),
          path('user/add/', user_view.user_add),
          path('user/<int:nid>/edit/', user_view.user_edit),
          path('user/<int:nid>/del/', user_view.user_del),

          # 靓号管理相关路由
          path('pretty/list/', pretty_view.pretty_list),
          #添加靓号
          path('pretty/add/', pretty_view.pretty_add),
          #修改靓号
          path('pretty/<int:nid>/edit/', pretty_view.pretty_edit),
          # 删除靓号
          path('pretty/<int:nid>/del/', pretty_view.pretty_del),
          #管理员账户管理
          #管理员列表
          path('admin/list/',admin_view.admin_list),
          # 新增管理员
          path('admin/add/',admin_view.admin_add),
          # 编辑管理员信息
          path('admin/<int:nid>/edit/',admin_view.admin_edit),
          # 重置管理员密码
          path('admin/<int:nid>/reset/',admin_view.admin_reset),
          # 删除管理员
          path('admin/<int:nid>/del/',admin_view.admin_del),

          #登录相关路由
          path('login/',acc_view.login),
          # 注销或者说退出登录
          path('logout/',acc_view.logout),
          # 动态生成验证码的路由
          path("image/code/",acc_view.image_code),

          # ajax测试任务管理
          path("task/test/list",task_view.task_test_list),
          path("task/test/ajax/",task_view.task_test_ajax),
          # ajax 请求发送表单数据
          path("task/test/ajax2/",task_view.task_test_ajax2),

          # 任务管理
          path("task/list/",task_view.task_list),
          path("task/add/",task_view.task_add),
          # 订单管理
          path("order/list/",order_view.order_list),
          path("order/add/",order_view.order_add),
          path("order/del/",order_view.order_del),
          # 处理Ajax查询请求
          path("order/detail/",order_view.order_detail),
          path("order/<int:eId>/edit/",order_view.order_edit),
          path("order/edit2/",order_view.order_edit2),

          # 图表
          path("chart/list",chart_view.chart_list),
          # 处理柱状图的请求
          path("chart/bar/",chart_view.chart_bar),
          # 处理饼状图请求
          path("chart/pie/",chart_view.chart_pie),
          # 处理这些图请求
          path("chart/line/",chart_view.chart_line),

          # 文件上传相关路由,改为用ModelForm上传
          path("upload/list/",upload_view.upload_list),
          # 路由django的Form组件来实现上传功能
          path("upload/form/",upload_view.upload_form),
          # 使用ModelForm上传的便捷方式
          path("upload/modelform/",upload_view.upload_model_form),

          # 城市列表
          path("city/list/",city_view.city_list),
          # 新增城市
          path("city/add/",city_view.city_add),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

04_django/django_proj1/django_proj1/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

04_django/mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from mySiteApp import views




urlpatterns = [
    # path('admin/', admin.site.urls),
    path(r'', views.home),
    path('index/', views.index),
    path('reg/', views.register),
    path('userlist/', views.user_list),
    path('tpl/', views.tpl),
    path('movies/', views.movies),
    path('req_test/', views.reqTest),
    path('login/', views.login),
    path('orm/', views.orm),
    # path('users/', views.showAll),
    path('info/list/', views.showAll),  #添加这两个路由是为了更加规范我们的路由写法
    # path('add/', views.addNew),
    path('info/add/', views.addNew),   #添加这两个路由是为了更加规范我们的路由写法
    path('info/delete/', views.deleteOne),   #规范我们的路由写法
] + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

04_django/day18/day16app/models.py
from django.db import models


class Admin(models.Model):
    """管理员表"""
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密  码", max_length=64)


# Create your models here.
class Department(models.Model):
    """部门表"""
    # id = models.BigAutoField(verbose_name="ID",primary_key=True)  #不需要写django会自动处理这个表字段
    title = models.CharField(verbose_name="标题", max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """员工表"""
    name = models.CharField(verbose_name="姓名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")  # 需要添加默
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2)
    create_time = models.DateField(verbose_name="入职时间")  # 把原来的DateTimeField改为DateField
    # 这个类型不对,它是没有约束的
    # dep_id=models.BigIntegerField(verbose_name="部门ID")
    # 这个类型有约束的,也就是外键
    # 只需要写dep,然后django会把它变为dep_id
    # 方式1,需要设置关联的表(类),还要设置表的关联的列,还需要设置部门被删除了,对应的员工数据会级联删除.
    dep = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", on_delete=models.CASCADE, default="选择部门")
    # 方式2.需要设置关联的表(类),还要设置表的关联的列,还需要设置可以置空,也就是部门被删除了,对应员工的部门变为空
    # dep = models.ForeignKey(to="Department", to_field="id",null=True,blank=True, on_delete=models.SET_NULL)
    gender_choices = (
        (0, "女"),
        (1, "男")
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices, default="选择性别")  # 注意django中性别的处理方式


# 靓号类
class PrettyNumber(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name="手机号码", max_length=11)
    price = models.IntegerField(verbose_name="价钱",default=2000)
    level_choice = (
        (1, "一级"),
        (2, "二级"),
        (3, "三级"),
        (4, "四级"),
    )
    level = models.SmallIntegerField(verbose_name="靓号等级", choices=level_choice, default=1)
    status_choice = (
        (0, "未占用"),
        (1, "已使用"),
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choice, default=0)

04_django/day16/day16app/views/admin_view.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from day16app import models  # 导入models因为以后可能里面会有很多类不能一个一个导入
from day16app.utils.pagination import Pagination
from day16app.form import day16forms


def admin_list(req):
    # 搜索功能
    term = {}
    kw = req.GET.get("kw", "")
    if kw:
        term["username__contains"] = kw

    admins = models.Admin.objects.filter(**term)
    # 分页
    # 1.实例化分页类的对象
    page_obj = Pagination(req, admins, page_size=3)
    # 2.获取分页数据
    page_query_set = page_obj.page_queryset
    # 3.获取分页器的html字符串
    page_str = page_obj.gen_html()
    return render(req, "admin_list.html", {"admins": page_query_set, "kw": kw, "page_str": page_str})


def admin_add(req):
    # 新增管理员
    if req.method == 'GET':
        form = day16forms.AdminAddForm()
        return render(req, "admin_add.html", {"form": form})
    # 获取post请求的数据并且进行数据校验
    form = day16forms.AdminAddForm(data=req.POST)
    if form.is_valid():  # 数据校验成功
        # 保存数据
        form.save(commit=True)
        return redirect("/admin/list")
    # 校验失败,需要停留在这个页面并且显示错误信息
    return render(req, "admin_add.html", {"form": form})


def admin_edit(req, nid):
    """修改管理员"""
    admin1 = models.Admin.objects.filter(id=nid).first()
    if req.method == "GET":
        form = day16forms.AdminEditForm(instance=admin1)
        return render(req, "admin_edit.html", {"form": form})  # 使用了验证器,这里就不要传递nid,获取不到的.
    # 获取post请求的数据并且进行数据校验
    form = day16forms.AdminEditForm(data=req.POST, instance=admin1)
    if form.is_valid():  # 数据校验成功
        # 保存数据
        form.save(commit=True)
        return redirect("/admin/list")
    # 校验失败,需要停留在这个页面并且显示错误信息
    return render(req, "admin_edit.html", {"form": form})


def admin_del(req, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect("/admin/list/")

04_django/day16/day16app/views/pretty_view.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from day16app import models  # 导入models因为以后可能里面会有很多类不能一个一个导入
from day16app.utils.pagination import Pagination
from day16app.form import day16forms


# 靓号管理函数.
def pretty_list(req):
    """靓号列表"""
    # addData()
    term = {}
    kw = req.GET.get("kw", "")
    if kw:
        term["mobile__contains"] = kw

    pretty_data = models.PrettyNumber.objects.filter(**term).order_by("-level")
    page_obj = Pagination(req, pretty_data)
    page_query_set = page_obj.page_queryset
    # 分页功能
    page_str = page_obj.gen_html()
    return render(req, "pretty_list.html", {"pretties": page_query_set, "kw": kw, "page_str": page_str})


def pretty_add(req):
    """新增靓号"""
    if req.method == "GET":
        form = day16forms.PrettyNumberAddForm()
        return render(req, "pretty_add.html", {"form": form})
    # 获取post请求的数据并且进行数据校验
    form = day16forms.PrettyNumberAddForm(data=req.POST)
    if form.is_valid():  # 数据校验成功
        # 保存数据
        form.save(commit=True)
        return redirect("/pretty/list")
    # 校验失败,需要停留在这个页面并且显示错误信息
    return render(req, "pretty_add.html", {"form": form})


def pretty_edit(req, nid):
    """修改靓号"""
    pretty_num = models.PrettyNumber.objects.filter(id=nid).first()
    if req.method == "GET":
        form = day16forms.PrettyNumberEditForm(instance=pretty_num)
        return render(req, "pretty_edit.html", {"form": form})  # 使用了验证器,这里就不要传递nid,获取不到的.
    # 获取post请求的数据并且进行数据校验
    form = day16forms.PrettyNumberEditForm(data=req.POST, instance=pretty_num)
    if form.is_valid():  # 数据校验成功
        # 保存数据
        form.save(commit=True)
        return redirect("/pretty/list")
    # 校验失败,需要停留在这个页面并且显示错误信息
    return render(req, "pretty_edit.html", {"form": form})


def pretty_del(req, nid):
    models.PrettyNumber.objects.filter(id=nid).delete()
    return redirect("/pretty/list/")

04_django/day16/day16app/views/user_view.py
from django.shortcuts import render, redirect
from day16app import models  # 导入models因为以后可能里面会有很多类不能一个一个导入
from day16app.utils.pagination import Pagination
from day16app.form import day16forms


def user_list(req):
    users = models.UserInfo.objects.all()
    # 分页
    # 1.实例化分页类的对象
    page_obj = Pagination(req, users, page_size=3)
    # 2.获取分页数据
    page_query_set = page_obj.page_queryset
    # 3.获取分页器的html字符串
    page_str = page_obj.gen_html()
    # 渲染数据
    return render(req, "user_list.html", {'users': page_query_set, "page_str": page_str})


def user_add(req):
    """新增用户"""
    if req.method == "GET":
        form = day16forms.UserInfoForm()
        return render(req, "user_add.html", {"form": form})
    # 获取post请求的数据并且进行数据校验
    form = day16forms.UserInfoForm(data=req.POST)
    if form.is_valid():  # 数据校验成功
        # 保存数据
        form.save(commit=True)
        return redirect("/user/list")
    # 校验失败,需要停留在这个页面并且显示错误信息
    return render(req, "user_add.html", {"form": form})




def user_edit(req, nid):
    """编辑用户信息"""
    # 查询数据
    user1 = models.UserInfo.objects.filter(id=nid).first()  # 放在这里是因为有2个地方需要用到这个user1
    if req.method == "GET":
        form = day16forms.UserInfoForm(instance=user1)
        return render(req, "user_edit.html", {"form": form, "nid": nid})
    # 获取post请求的数据并且进行数据校验
    form = day16forms.UserInfoForm(instance=user1, data=req.POST)  # 更新的时候需要两个参数来构造form对象:数据和需要更新的实例
    if form.is_valid():  # 数据校验成功
        # 保存数据
        form.save()  # 新增和更新都是使用这个方法,只是form里面的数据不一样
        return redirect("/user/list")
    # 校验失败,需要停留在这个页面并且显示错误信息
    return render(req, "user_edit.html", {"form": form})


def user_del(req, nid):
    """删除用户信息"""
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect("/user/list/")

04_django/day20/day16app/views/acc_view.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from day16app import models  # 导入models因为以后可能里面会有很多类不能一个一个导入
from day16app.utils.encrypt import md5
from day16app.utils.pagination import Pagination
from day16app.utils import day16forms
from day16app.utils.code import check_code
from io import BytesIO
from django import forms
from day16app.utils.basemform import BootstrapForm


class LoginForm(BootstrapForm):
    # 这里的字段名一定要和表单里面的name一样,并且要和Admin类里面的字段名一样,否则后面很难操作
    username = forms.CharField(label="用户名", widget=forms.TextInput)
    password = forms.CharField(label="密 码",widget=forms.PasswordInput(attrs={"autocomplete": "off"}, render_value=True))
    code = forms.CharField(label="验证码", widget=forms.TextInput(attrs={"autocomplete": "off"}),required=True)

    def clean_password(self):
        txt_pwd = self.cleaned_data.get("password")
        return md5(txt_pwd)  # 把获取到的密码进行md5加密


def login(req):
    if req.method == "GET":
        form = LoginForm()
        return render(req, "login.html", {"form": form})
    form = LoginForm(data=req.POST)
    if form.is_valid():
        # 验证码校验,这里需要用到一个小技巧,调用form.clean_data.pop(xxx)方法
        user_input_code = form.cleaned_data.pop('code')  # 这里需要使用pop是因为我们的数据库里面没有code,而我们下面需要用form的字段去数据库中校验,这样子会有问题
        code = req.session.get("image_code", "")
        if user_input_code.upper() != code.upper():
            form.add_error("code", "验证码错误")
            return render(req, "login.html", {"form": form})  # 验证码错误不允许跳转还得停留在登录页面
        # 普通form是没有save方法的,注意modelform才有
        # 写法1,
        # user = form.cleaned_data.get("username")
        # pwd = form.cleaned_data.get("password")
        # admin = models.Admin.objects.filter(username=user,password=pwd).first()

        # 写法2
        admin = models.Admin.objects.filter(**form.cleaned_data).first() # 验证码校验通过,再进行用户名和密码校验
        # 如果用户名或者密码错误,就找不到数据.在渲染登录页面,也就是不让他跳转
        if not admin:
            form.add_error("password", "用户名或者密码错误!!!")  # 这个方法不需要修改模板的内容
            return render(req, "login.html", {"form": form})  # 用户信息验证失败,也就是登录失败
            # return render(req, "login.html", {"form": form,"error_msg":"用户名或者密码错误"})
        # 登录成功,生成随机字符串写到用户浏览器的cookie中,在django中这个操作比较简单.
        req.session["info"] = {"id": admin.id, "name": admin.username}
        req.session.set_expiry(60*60*24*7) # 设置用户7天免登录,这个其实可以根据你自己的需求来设置
        return redirect("/admin/list/")  # 登录成功,跳转到管理员账户页面
    return render(req, "login.html", {"form": form})  # form表单校验失败


def logout(req):
    """注销功能"""
    # 注销也很简单,就是把session的数据清空
    req.session.clear()
    # 然后重定向到登录页面
    return redirect("/login/")


def image_code(req):
    '''生成图片验证码'''
    img, code_str = check_code()
    print(code_str)
    # 把生成的验证码保存到session
    req.session["image_code"] = code_str
    # 还要设置session的过期时间
    req.session.set_expiry(60)
    stream = BytesIO()
    img.save(stream, "png")
    return HttpResponse(stream.getvalue())

04_django/day20/day16app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8" />
    <title>用户登录</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>

        .account {
           width:400px;
           border:1px solid #dddddd;
           border-radius: 5px;
           box-shadow: 5px 5px 20px #aaa;

          margin-left: auto;
          margin-right: auto;
          margin-top: 80px;
          padding: 20px 40px;
        }


        .account h2{
           margin-top: 10px;
           text-align:center;
        }

    </style>

</head>
<body>
   <div class="account">
       <h2>用户登录</h2>
       <form method="post" novalidate>
           {% csrf_token %}
           <div class="form-group">
               <label>用户名</label>
               {{form.username}}
               <span style="color: red;">{{ form.username.errors.0 }}</span>

           </div>
           <div class="form-group">
               <label>密 码</label>
               {{form.password}}
               <span style="color: red;">{{ form.password.errors.0 }}</span>
           </div>
           <div class="form-group">
               <label for="id_code">图片验证码</label>
               <div class="row">
                   <div class="col-xs-7">
{#                       <input type="text" name="code" class="form-control" placeholder="输入图片验证码" id="id_code" required="">#}
                       {{ form.code }}
                       <span style="color: red;">{{ form.code.errors.0 }}</span>
                   </div>
                   <div class="col-xs-5">
                       <img id="image_code" src="/image/code/" alt="">
                   </div>
               </div>
           </div>

           <input type="submit" class="btn btn-primary" value="登录">
       </form>
   </div>
</body>
</html>

04_django/day20/day16app/templates/pretty_list.html
{% extends 'layout.html' %}

{% block title %}
<title>靓号列表</title>
{% endblock %}

{% block content %}
<div class="container">
        <div style="margin-bottom: 5px;" class="clearfix">
              <a href="/pretty/add/" class="btn btn-primary">
                  <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                  新增靓号
              </a>
            <div style="float: right;width:300px;">
                <form method="get">
                    <div class="input-group">
                      <input type="text" name="kw" class="form-control" placeholder="Search for..." value="{{ kw }}">
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>
          </div>
        <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading">
                  <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                  靓号列表
              </div>

             <table class="table table-bordered table-responsive">
              <thead>
              <tr>
                  <th>ID</th>
                  <th>手机号</th>
                  <th>价格</th>
                  <th>级别</th>
                  <th>状态</th>
              </tr>
              </thead>
              <tbody>
              {% for pr in pretties %}
              <tr>
                  <td>{{ pr.id }}</td>
                  <td>{{ pr.mobile }}</td>
                  <td>{{pr.price}}</td>
                  <td>{{ pr.get_level_display }}</td>
                  <td>{{ pr.get_status_display }}</td>
                  <td>
{#                      <a href="/dep/edit/?nid={{ dep.id }}" class="btn btn-success btn-xs">编辑</a>#}
                      <a href="/pretty/{{ pr.id }}/edit/" class="btn btn-success btn-xs">编辑</a>
                      <a href="/pretty/{{ pr.id}}/del/" class="btn btn-danger btn-xs">删除</a>
                  </td>
              </tr>
              {% endfor %}
              </tbody>
          </table>
        </div>
         {#    弹性盒子     #}
         <div class="clearfix">
            {#     分页组件        #}
             <ul class="pagination">
                    {{page_str}}
             </ul>

         </div>
</div>
{% endblock %}

04_django/day20/day16app/templates/task_list.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    <title>Ajax请求学习</title>
{% endblock %}

{% block content %}
  <div class="container">
     <h4>创建任务</h4>
     {# 任务表单 #}
     <div class="panel panel-default">
         <div class="panel-heading">任务表单</div>
         <div class="panel-body">
             <form id="taskForm"> {#这里使用ajax提交form里面需要一个id属性#}
{#               {% csrf_token %}#} {#这里使用ajax提交form里面不需要token#}
               <div class="clearfix">
                 {% for item in form %}
                  <div class="col-xs-6">
                     <div class="form-group" style="position: relative;margin-bottom: 30px;">
                       {{ item.label }}
                       {{ item }}
                     <span class="error-msg" style="color: red;position: absolute;margin-top: 5px;"></span>
                     </div>
                  </div>
                 {% endfor %}
                  <div class="col-xs-12">
                    <button type="button" id="btn" class="btn btn-success">保存任务</button> {#这里不是submit因为我们用ajax提交#}
                  </div>
               </div>
            </form>
         </div>
     </div>
  </div>
    <hr>
   {# 任务列表   #}
  <div class="container">
    <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading">
                  <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                  任务列表
              </div>

             <table class="table table-bordered table-responsive">
              <thead>
              <tr>
                  <th>ID</th>
                  <th>级别</th>
                  <th>标题</th>
                  <th>负责人</th>
                  <th>操作</th>
              </tr>
              </thead>
              <tbody>
              {% for t in tasks %}
              <tr>
                  <td>{{ t.id }}</td>
                  <td>{{ t.get_level_display }}</td>
                  <td>{{ t.title }}</td>
                  <td>{{ t.user }}</td>
                  <td>
{#                      <a href="/dep/edit/?nid={{ dep.id }}" class="btn btn-success btn-xs">编辑</a>#}
                      <a href="#" class="btn btn-success btn-xs">编辑</a>
                      <a href="#" class="btn btn-danger btn-xs">删除</a>
                  </td>
              </tr>
              {% endfor %}
              </tbody>
          </table>
          </div>
        {#  分页组件      #}
        <ul class="pagination">
              {{ page_str }}
          </ul>
  </div>

{% endblock %}

{% block js %}
    <script>
      $(function () {
          $("#btn").click(function () {
              //先把上一次保存的错误信息清空,因为class名字使用显示错误的span的class都一样.
              $(".error-msg").empty();
              $.ajax({
                  url:"/task/add/",
                  type:"post",
                  data:$("#taskForm").serialize(),
                  dataType:"JSON",
                  success:function (ret) {
                      {#console.log(ret)#}
                      if(ret.status){
                          alert("添加任务成功!")
                          //用js刷新页面,否则新增加的数据不会体现在页面上
                          location.reload()
                      } else{
                          $.each(ret.errors,function (name, data) {
                              $("#id_"+name).next().text(data[0])

                          })
                      }
                  }
              })
          })
      })
    </script>
{% endblock %}

04_django/day20/day16app/templates/user_add.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}
    <title>新增用户</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/font-awesome4.7.0/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker1.9.0/css/bootstrap-datepicker.css' %}">
{% endblock %}


{% block content %}
 <div>
    <div class="container">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
              <h3 class="panel-title">新建用户</h3>
          </div>
          <div class="panel-body">
          {# 表单  #}
           <form action="/user/add/" method="post" novalidate>
               {% csrf_token %}
               {% for item in form %}
                  <div class="form-group">
                    {{ item.label }}
                      {{ item }}
                      <span style="color: red;"> {{ item.errors.0 }}</span>
                  </div>
               {% endfor %}

              <button type="submit" class="btn btn-success">保 存</button>
        </form>

          </div>
        </div>

    </div>
</div>
{% endblock %}

 {% block js %}
     <script src="{% static 'plugins/bootstrap-datepicker1.9.0/js/bootstrap-datepicker.js' %}"></script>
     <script src="{% static 'plugins/bootstrap-datepicker1.9.0/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
     <script>
        $(function () {
            $('#id_create_time').datepicker({
                format:"yyyy-mm-dd",
                startDate:0,
                language:"zh-CN",
                autoclose:true
            });
        })
    </script>
 {% endblock %}